#!/usr/bin/env python3
"""Bundle src/ into the single .wh.cpp file Windhawk expects.

Windhawk compiles one file per mod, but a 1000-line file is no fun to work in,
so the mod lives in src/ as a set of modules that each include src/common.h.
This script concatenates them, in a fixed order, behind the Windhawk metadata
block from src/metadata.wh, and writes build/<mod id>.wh.cpp.

Because every cross-file declaration is in common.h, the concatenation order
does not affect correctness - it is fixed only so the output is reproducible
and reads top-down.

    python tools/bundle.py                 -> build/<id>.wh.cpp
    python tools/bundle.py -o dist         -> dist/<id>.wh.cpp
    python tools/bundle.py --print-name    -> just print the output file name
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
METADATA = SRC / "metadata.wh"
HEADER = SRC / "common.h"

# Fixed order, roughly "leaves first, lifecycle last". Every .cpp in src/ must
# be listed; bundling fails otherwise so a new module can't be silently missed.
MODULES = [
    "settings.cpp",
    "window_info.cpp",
    "frame_geometry.cpp",
    "decorations.cpp",
    "titlebar.cpp",
    "hotkey.cpp",
    "startmenu.cpp",
    "drag.cpp",
    "hooks.cpp",
    "mod.cpp",
]

# Lines that only exist to make a module a standalone translation unit.
LOCAL_INCLUDE = re.compile(r'^\s*#include\s*"')
PRAGMA_ONCE = re.compile(r"^\s*#pragma\s+once\s*$")


def read_metadata() -> tuple[str, str, str]:
    """Returns (text, mod id, version) from src/metadata.wh."""
    text = METADATA.read_text(encoding="utf-8")
    fields = {}
    for key in ("id", "version"):
        m = re.search(rf"^//\s*@{key}\s+(\S+)\s*$", text, re.MULTILINE)
        if not m:
            sys.exit(f"error: @{key} not found in {METADATA.name}")
        fields[key] = m.group(1)
    return text, fields["id"], fields["version"]


def strip_scaffolding(text: str) -> str:
    kept = [
        line
        for line in text.splitlines()
        if not LOCAL_INCLUDE.match(line) and not PRAGMA_ONCE.match(line)
    ]
    return "\n".join(kept).strip("\n")


def banner(title: str) -> str:
    rule = "/" * 80
    return f"{rule}\n// {title}\n{rule}"


def bundle() -> tuple[str, str]:
    if not METADATA.is_file():
        sys.exit(f"error: missing {METADATA}")
    if not HEADER.is_file():
        sys.exit(f"error: missing {HEADER}")

    metadata, mod_id, _version = read_metadata()

    listed = set(MODULES)
    present = {p.name for p in SRC.glob("*.cpp")}
    if missing := sorted(present - listed):
        sys.exit(
            "error: these modules exist in src/ but are not listed in "
            f"tools/bundle.py MODULES: {', '.join(missing)}"
        )
    if absent := sorted(listed - present):
        sys.exit(f"error: listed modules not found in src/: {', '.join(absent)}")

    parts = [
        metadata.rstrip("\n"),
        "",
        "// This file is generated by tools/bundle.py from src/ - do not edit it",
        "// directly; edit the modules in src/ and bundle again.",
        "",
        banner("src/common.h"),
        strip_scaffolding(HEADER.read_text(encoding="utf-8")),
    ]
    for name in MODULES:
        parts += [
            "",
            banner(f"src/{name}"),
            strip_scaffolding((SRC / name).read_text(encoding="utf-8")),
        ]

    return mod_id, "\n".join(parts) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "-o",
        "--out-dir",
        default=str(ROOT / "build"),
        help="directory for the generated file (default: build/)",
    )
    ap.add_argument(
        "--print-name",
        action="store_true",
        help="print the output file name and exit without writing",
    )
    args = ap.parse_args()

    mod_id, text = bundle()
    name = f"{mod_id}.wh.cpp"
    if args.print_name:
        print(name)
        return

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / name
    out_path.write_text(text, encoding="utf-8", newline="\n")
    print(f"{out_path}  ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
